dist: xenial
language: python
jobs:
  include:
  - python: "2.6"
    dist: trusty
  - python: "2.7"
  - python: "3.2"
    dist: trusty
  - python: "3.3"
    dist: trusty
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7-dev"
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then if_sphinx=:; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then if_sphinx=:; fi
install:
- pip install pydiatra $pyflakes
- $if_sphinx pip install sphinx
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- python -m pydiatra .
- pyflakes .
- $if_sphinx python setup.py build_doc
- LC_ALL=C python setup.py --version
- python setup.py install
- cd /
- python -c 'import keyboardleds'
- curl -fsS https://pypi.org/simple/keyboardleds/; [ $? -eq 22 ]

# vim:ts=2 sts=2 sw=2 et
