#!/usr/bin/python

TEMPERATURE_LIMIT = 75.0
# Temperatures above this limit are consider bogus, and thus ignored.
TEMPERATURE_BOGUS_LIMIT = 200.0
SLEEP = 5
BLINK_SLEEP = 0.2

import glob
import re
import subprocess
import time

import keyboardleds

def drop_privileges():
    import pwd
    import os
    uid = pwd.getpwnam('nobody').pw_uid
    os.setuid(uid)

event_device = glob.glob('/dev/input/by-path/*-event-kbd')[0]
ledkit = keyboardleds.LedKit(event_device)
drop_privileges()
led = ledkit.caps_lock

temperature_re = re.compile('^ +temp[0-9]+_input: ([0-9.]+)$')

while True:
    alert = False
    sensors = subprocess.Popen(['sensors', '-u'], stdout=subprocess.PIPE)
    for line in sensors.stdout:
        line = line.rstrip()
        match = temperature_re.match(line)
        if match is not None:
            temperature = match.group(1)
            temperature = float(temperature)
            if TEMPERATURE_LIMIT < temperature < TEMPERATURE_BOGUS_LIMIT:
                alert = True
    sensors.wait()
    if alert:
        i = 0
        while i * BLINK_SLEEP < SLEEP:
            if i & 1 == 0:
                led.set()
            else:
                led.reset()
            time.sleep(BLINK_SLEEP)
            i += 1
        led.reset()
    else:
        time.sleep(SLEEP)

# vim:ts=4 sw=4 et
